from __future__ import annotations

TYPE_KEY: str
VERSION_KEY: str
SCHEMA_VERSION: int
ENUM: str
GAME_OBJECT_REF: str
COMPONENT_REF: str
ASSET_REF: str
SERIALIZABLE_OBJECT: str

def make_document(document_type: str, **payload) -> dict: ...
def make_enum(enum_type: str, name: str) -> dict: ...
def make_game_object_ref(object_id: int) -> dict: ...
def make_component_ref(game_object_id: int, component_type: str) -> dict: ...
def make_asset_ref(asset_type: str, guid: str, path_hint: str = "") -> dict: ...
def make_serializable_object(type_id: str, fields: dict) -> dict: ...
