from __future__ import annotations

from typing import Optional
from Infernux.lib import InxPhysicMaterial as NativePhysicMaterial

class PhysicMaterial:
    def __init__(self, native: Optional[NativePhysicMaterial] = ...) -> None: ...
    @staticmethod
    def load(path: str) -> Optional[PhysicMaterial]: ...
    @staticmethod
    def load_by_guid(guid: str) -> Optional[PhysicMaterial]: ...
    @property
    def native(self) -> NativePhysicMaterial: ...
    @property
    def name(self) -> str: ...
    @property
    def guid(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    friction: float
    bounciness: float
    friction_combine: int
    bounce_combine: int
    def serialize_document(self) -> dict: ...
    def deserialize_document(self, document: dict) -> None: ...
    def save(self, path: str = ...) -> None: ...
